### ISSUE TITLE
annotation

### ISSUE THREAD

**Issue by fcgportal** [yihchii/hippie#1]
Dear ‘hippie’ developers, Thanks for developing ‘hippie’! It is of a great interest for us to be able to discover enhancer–target gene interactions using Hi-C. Since our in-house data is based on current Gencode Annotation (Ensembl v79), just wondering is there an instruction to produce "hippie_annot_hg38/database" using Ensembl v79 ? We would be very appreciable if you could advise us what could be amend in our procedure. Thank you again.

**Comment by yihhwang** [comment]
Hi @dreamingest , 

Thanks you for your message. Please refer to our parsed annotation data at: [hippie website](http://wanglab.pcbi.upenn.edu/hippie/). In the `hippie_annot_hg19.tar.gz` package, you could find `database/download_read.txt` and `database/README_BED.sh` as the scripts for generating the `hippie_annot_hg19/database/` folder. Please amend `hg19` toward `hg38` from the two scripts, in order to work on the latest (hg38) assembly.

**Comment by fcgportal** [comment]
Hi Yihchii,
Thank you so much for your kind help. I've already produced a "hippie_annot_hg38/database". It seemed good! One more thing, do you have any suggestion on making "hippie_annot_hg38/chromosomes" other than just liftover it from hg19 to hg38? Thank you again.

**Comment by yihhwang** [comment]
Hi @dreamingest , 
We suggest you to do liftover from hg19 to hg38 for the `chromosomes /` folder. The actual calculation of mappability and gc content requires not only parsing but also re-mapping on the simulated data, and liftover is a relatively efficient way for getting the reliable coordinates with their values.
